defmodule Ashes.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # alter table(:packages) do
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :docs_url
    # 
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :hex_url
    # 
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :tags
    # end
    # 
    create unique_index(:packages, [:github_repo_handle],
             name: "packages_by_github_repo_handle_index"
           )

    create unique_index(:packages, [:package], name: "packages_by_package_index")
  end

  def down do
    drop_if_exists unique_index(:packages, [:package], name: "packages_by_package_index")

    drop_if_exists unique_index(:packages, [:github_repo_handle],
                     name: "packages_by_github_repo_handle_index"
                   )

    # alter table(:packages) do
    # This is the `down` migration of the statement:
    #
    #     remove :tags
    #
    # 
    # add :tags, :text
    # This is the `down` migration of the statement:
    #
    #     remove :hex_url
    #
    # 
    # add :hex_url, :text
    # This is the `down` migration of the statement:
    #
    #     remove :docs_url
    #
    # 
    # add :docs_url, :text
    # end
    # 
  end
end
