defmodule Ashes.Repo.Migrations.InitialDataModel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tags, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:packages, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :github_repo_handle, :text
      add :docs_url, :text
      add :hex_url, :text
      add :description, :text
      add :tags, :text
      add :status, :text
      add :kind, :text
      add :official, :boolean
      add :category, :text, null: false
      add :package, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:package_tags, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :tag_id, :uuid, null: false
      add :package_id, :uuid, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:package_tags)

    drop table(:packages)

    drop table(:tags)
  end
end
