defmodule Ashes.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:package_tags, [:package_id, :tag_id],
             name: "package_tags_by_package_and_tag_index"
           )
  end

  def down do
    drop_if_exists unique_index(:package_tags, [:package_id, :tag_id],
                     name: "package_tags_by_package_and_tag_index"
                   )
  end
end
